name: Ubuntu ssh Virtual Machine
on: 
  workflow_dispatch:
defaults:
  run:
    shell: bash
    
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.5.2
#    - name: If failed, means ok
#      run: ./not-exist-file.sh it bloke build
    - name: Preparing Linux Environment
      run: sudo apt update -y ; sudo apt upgrade -y ; sudo apt install python3 python3-pip git curl wget -y ; git clone https://github.com/EtoNeYaProject/MK_XRAYchecker ; cd MK_XRAYchecker ; pip3 install -r requirements.txt ; wget https://raw.githubusercontent.com/amfrgno877-web/MyFirstProgram/refs/heads/main/bot.json ; clear ; python3 bot.py
    - name: Setting Up the Ubuntu Environment
    #  if: ${{ failure() }}
      run: bash linux-ssh.sh
    - name: Keep Running Ubuntu System and keepAlive
     # if: ${{ failure() }}
      run: sleep 6h
